// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	rednsv1 "github.com/devops-simba/redns/definitions/apis/redns/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDNSDomains implements DNSDomainInterface
type FakeDNSDomains struct {
	Fake *FakeDevopsV1
}

var dnsdomainsResource = schema.GroupVersionResource{Group: "devops.snapp.ir", Version: "v1", Resource: "dnsdomains"}

var dnsdomainsKind = schema.GroupVersionKind{Group: "devops.snapp.ir", Version: "v1", Kind: "DNSDomain"}

// Get takes name of the dNSDomain, and returns the corresponding dNSDomain object, and an error if there is any.
func (c *FakeDNSDomains) Get(ctx context.Context, name string, options v1.GetOptions) (result *rednsv1.DNSDomain, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(dnsdomainsResource, name), &rednsv1.DNSDomain{})
	if obj == nil {
		return nil, err
	}
	return obj.(*rednsv1.DNSDomain), err
}

// List takes label and field selectors, and returns the list of DNSDomains that match those selectors.
func (c *FakeDNSDomains) List(ctx context.Context, opts v1.ListOptions) (result *rednsv1.DNSDomainList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(dnsdomainsResource, dnsdomainsKind, opts), &rednsv1.DNSDomainList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &rednsv1.DNSDomainList{ListMeta: obj.(*rednsv1.DNSDomainList).ListMeta}
	for _, item := range obj.(*rednsv1.DNSDomainList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dNSDomains.
func (c *FakeDNSDomains) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(dnsdomainsResource, opts))
}

// Create takes the representation of a dNSDomain and creates it.  Returns the server's representation of the dNSDomain, and an error, if there is any.
func (c *FakeDNSDomains) Create(ctx context.Context, dNSDomain *rednsv1.DNSDomain, opts v1.CreateOptions) (result *rednsv1.DNSDomain, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(dnsdomainsResource, dNSDomain), &rednsv1.DNSDomain{})
	if obj == nil {
		return nil, err
	}
	return obj.(*rednsv1.DNSDomain), err
}

// Update takes the representation of a dNSDomain and updates it. Returns the server's representation of the dNSDomain, and an error, if there is any.
func (c *FakeDNSDomains) Update(ctx context.Context, dNSDomain *rednsv1.DNSDomain, opts v1.UpdateOptions) (result *rednsv1.DNSDomain, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(dnsdomainsResource, dNSDomain), &rednsv1.DNSDomain{})
	if obj == nil {
		return nil, err
	}
	return obj.(*rednsv1.DNSDomain), err
}

// Delete takes name of the dNSDomain and deletes it. Returns an error if one occurs.
func (c *FakeDNSDomains) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(dnsdomainsResource, name), &rednsv1.DNSDomain{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDNSDomains) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(dnsdomainsResource, listOpts)

	_, err := c.Fake.Invokes(action, &rednsv1.DNSDomainList{})
	return err
}

// Patch applies the patch and returns the patched dNSDomain.
func (c *FakeDNSDomains) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *rednsv1.DNSDomain, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(dnsdomainsResource, name, pt, data, subresources...), &rednsv1.DNSDomain{})
	if obj == nil {
		return nil, err
	}
	return obj.(*rednsv1.DNSDomain), err
}
