// Code generated by lister-gen. DO NOT EDIT.

package v1

// DNSDomainListerExpansion allows custom methods to be added to
// DNSDomainLister.
type DNSDomainListerExpansion interface{}

// DNSLoadBalancerListerExpansion allows custom methods to be added to
// DNSLoadBalancerLister.
type DNSLoadBalancerListerExpansion interface{}

// DNSRecordListerExpansion allows custom methods to be added to
// DNSRecordLister.
type DNSRecordListerExpansion interface{}
