// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/devops-simba/redns/controller/pkg/apis/redns/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DNSDomainLister helps list DNSDomains.
// All objects returned here must be treated as read-only.
type DNSDomainLister interface {
	// List lists all DNSDomains in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DNSDomain, err error)
	// Get retrieves the DNSDomain from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.DNSDomain, error)
	DNSDomainListerExpansion
}

// dNSDomainLister implements the DNSDomainLister interface.
type dNSDomainLister struct {
	indexer cache.Indexer
}

// NewDNSDomainLister returns a new DNSDomainLister.
func NewDNSDomainLister(indexer cache.Indexer) DNSDomainLister {
	return &dNSDomainLister{indexer: indexer}
}

// List lists all DNSDomains in the indexer.
func (s *dNSDomainLister) List(selector labels.Selector) (ret []*v1.DNSDomain, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.DNSDomain))
	})
	return ret, err
}

// Get retrieves the DNSDomain from the index for a given name.
func (s *dNSDomainLister) Get(name string) (*v1.DNSDomain, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("dnsdomain"), name)
	}
	return obj.(*v1.DNSDomain), nil
}
