// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/devops-simba/redns/controller/pkg/apis/redns/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DNSRecordLister helps list DNSRecords.
// All objects returned here must be treated as read-only.
type DNSRecordLister interface {
	// List lists all DNSRecords in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.DNSRecord, err error)
	// Get retrieves the DNSRecord from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.DNSRecord, error)
	DNSRecordListerExpansion
}

// dNSRecordLister implements the DNSRecordLister interface.
type dNSRecordLister struct {
	indexer cache.Indexer
}

// NewDNSRecordLister returns a new DNSRecordLister.
func NewDNSRecordLister(indexer cache.Indexer) DNSRecordLister {
	return &dNSRecordLister{indexer: indexer}
}

// List lists all DNSRecords in the indexer.
func (s *dNSRecordLister) List(selector labels.Selector) (ret []*v1.DNSRecord, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.DNSRecord))
	})
	return ret, err
}

// Get retrieves the DNSRecord from the index for a given name.
func (s *dNSRecordLister) Get(name string) (*v1.DNSRecord, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("dnsrecord"), name)
	}
	return obj.(*v1.DNSRecord), nil
}
