// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/devops-simba/redns/controller/pkg/apis/redns/v1"
	scheme "github.com/devops-simba/redns/controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DNSDomainsGetter has a method to return a DNSDomainInterface.
// A group's client should implement this interface.
type DNSDomainsGetter interface {
	DNSDomains() DNSDomainInterface
}

// DNSDomainInterface has methods to work with DNSDomain resources.
type DNSDomainInterface interface {
	Create(ctx context.Context, dNSDomain *v1.DNSDomain, opts metav1.CreateOptions) (*v1.DNSDomain, error)
	Update(ctx context.Context, dNSDomain *v1.DNSDomain, opts metav1.UpdateOptions) (*v1.DNSDomain, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DNSDomain, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DNSDomainList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DNSDomain, err error)
	DNSDomainExpansion
}

// dNSDomains implements DNSDomainInterface
type dNSDomains struct {
	client rest.Interface
}

// newDNSDomains returns a DNSDomains
func newDNSDomains(c *RednsV1Client) *dNSDomains {
	return &dNSDomains{
		client: c.RESTClient(),
	}
}

// Get takes name of the dNSDomain, and returns the corresponding dNSDomain object, and an error if there is any.
func (c *dNSDomains) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DNSDomain, err error) {
	result = &v1.DNSDomain{}
	err = c.client.Get().
		Resource("dnsdomains").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DNSDomains that match those selectors.
func (c *dNSDomains) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DNSDomainList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DNSDomainList{}
	err = c.client.Get().
		Resource("dnsdomains").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dNSDomains.
func (c *dNSDomains) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("dnsdomains").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dNSDomain and creates it.  Returns the server's representation of the dNSDomain, and an error, if there is any.
func (c *dNSDomains) Create(ctx context.Context, dNSDomain *v1.DNSDomain, opts metav1.CreateOptions) (result *v1.DNSDomain, err error) {
	result = &v1.DNSDomain{}
	err = c.client.Post().
		Resource("dnsdomains").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dNSDomain).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dNSDomain and updates it. Returns the server's representation of the dNSDomain, and an error, if there is any.
func (c *dNSDomains) Update(ctx context.Context, dNSDomain *v1.DNSDomain, opts metav1.UpdateOptions) (result *v1.DNSDomain, err error) {
	result = &v1.DNSDomain{}
	err = c.client.Put().
		Resource("dnsdomains").
		Name(dNSDomain.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dNSDomain).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dNSDomain and deletes it. Returns an error if one occurs.
func (c *dNSDomains) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("dnsdomains").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dNSDomains) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("dnsdomains").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dNSDomain.
func (c *dNSDomains) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DNSDomain, err error) {
	result = &v1.DNSDomain{}
	err = c.client.Patch(pt).
		Resource("dnsdomains").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
