// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/devops-simba/redns/controller/pkg/apis/redns/v1"
	scheme "github.com/devops-simba/redns/controller/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DNSLoadBalancersGetter has a method to return a DNSLoadBalancerInterface.
// A group's client should implement this interface.
type DNSLoadBalancersGetter interface {
	DNSLoadBalancers() DNSLoadBalancerInterface
}

// DNSLoadBalancerInterface has methods to work with DNSLoadBalancer resources.
type DNSLoadBalancerInterface interface {
	Create(ctx context.Context, dNSLoadBalancer *v1.DNSLoadBalancer, opts metav1.CreateOptions) (*v1.DNSLoadBalancer, error)
	Update(ctx context.Context, dNSLoadBalancer *v1.DNSLoadBalancer, opts metav1.UpdateOptions) (*v1.DNSLoadBalancer, error)
	UpdateStatus(ctx context.Context, dNSLoadBalancer *v1.DNSLoadBalancer, opts metav1.UpdateOptions) (*v1.DNSLoadBalancer, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.DNSLoadBalancer, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.DNSLoadBalancerList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DNSLoadBalancer, err error)
	DNSLoadBalancerExpansion
}

// dNSLoadBalancers implements DNSLoadBalancerInterface
type dNSLoadBalancers struct {
	client rest.Interface
}

// newDNSLoadBalancers returns a DNSLoadBalancers
func newDNSLoadBalancers(c *RednsV1Client) *dNSLoadBalancers {
	return &dNSLoadBalancers{
		client: c.RESTClient(),
	}
}

// Get takes name of the dNSLoadBalancer, and returns the corresponding dNSLoadBalancer object, and an error if there is any.
func (c *dNSLoadBalancers) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DNSLoadBalancer, err error) {
	result = &v1.DNSLoadBalancer{}
	err = c.client.Get().
		Resource("dnsloadbalancers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DNSLoadBalancers that match those selectors.
func (c *dNSLoadBalancers) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DNSLoadBalancerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.DNSLoadBalancerList{}
	err = c.client.Get().
		Resource("dnsloadbalancers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dNSLoadBalancers.
func (c *dNSLoadBalancers) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("dnsloadbalancers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dNSLoadBalancer and creates it.  Returns the server's representation of the dNSLoadBalancer, and an error, if there is any.
func (c *dNSLoadBalancers) Create(ctx context.Context, dNSLoadBalancer *v1.DNSLoadBalancer, opts metav1.CreateOptions) (result *v1.DNSLoadBalancer, err error) {
	result = &v1.DNSLoadBalancer{}
	err = c.client.Post().
		Resource("dnsloadbalancers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dNSLoadBalancer).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dNSLoadBalancer and updates it. Returns the server's representation of the dNSLoadBalancer, and an error, if there is any.
func (c *dNSLoadBalancers) Update(ctx context.Context, dNSLoadBalancer *v1.DNSLoadBalancer, opts metav1.UpdateOptions) (result *v1.DNSLoadBalancer, err error) {
	result = &v1.DNSLoadBalancer{}
	err = c.client.Put().
		Resource("dnsloadbalancers").
		Name(dNSLoadBalancer.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dNSLoadBalancer).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *dNSLoadBalancers) UpdateStatus(ctx context.Context, dNSLoadBalancer *v1.DNSLoadBalancer, opts metav1.UpdateOptions) (result *v1.DNSLoadBalancer, err error) {
	result = &v1.DNSLoadBalancer{}
	err = c.client.Put().
		Resource("dnsloadbalancers").
		Name(dNSLoadBalancer.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dNSLoadBalancer).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dNSLoadBalancer and deletes it. Returns an error if one occurs.
func (c *dNSLoadBalancers) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("dnsloadbalancers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dNSLoadBalancers) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("dnsloadbalancers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dNSLoadBalancer.
func (c *dNSLoadBalancers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DNSLoadBalancer, err error) {
	result = &v1.DNSLoadBalancer{}
	err = c.client.Patch(pt).
		Resource("dnsloadbalancers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
