// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/devops-simba/redns/controller/pkg/apis/redns/v1"
	"github.com/devops-simba/redns/controller/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type RednsV1Interface interface {
	RESTClient() rest.Interface
	DNSDomainsGetter
	DNSLoadBalancersGetter
	DNSRecordsGetter
}

// RednsV1Client is used to interact with features provided by the redns.devops.snapp.ir group.
type RednsV1Client struct {
	restClient rest.Interface
}

func (c *RednsV1Client) DNSDomains() DNSDomainInterface {
	return newDNSDomains(c)
}

func (c *RednsV1Client) DNSLoadBalancers() DNSLoadBalancerInterface {
	return newDNSLoadBalancers(c)
}

func (c *RednsV1Client) DNSRecords() DNSRecordInterface {
	return newDNSRecords(c)
}

// NewForConfig creates a new RednsV1Client for the given config.
func NewForConfig(c *rest.Config) (*RednsV1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &RednsV1Client{client}, nil
}

// NewForConfigOrDie creates a new RednsV1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *RednsV1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new RednsV1Client for the given RESTClient.
func New(c rest.Interface) *RednsV1Client {
	return &RednsV1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *RednsV1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
