// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/devops-simba/redns/controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// DNSDomains returns a DNSDomainInformer.
	DNSDomains() DNSDomainInformer
	// DNSLoadBalancers returns a DNSLoadBalancerInformer.
	DNSLoadBalancers() DNSLoadBalancerInformer
	// DNSRecords returns a DNSRecordInformer.
	DNSRecords() DNSRecordInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// DNSDomains returns a DNSDomainInformer.
func (v *version) DNSDomains() DNSDomainInformer {
	return &dNSDomainInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// DNSLoadBalancers returns a DNSLoadBalancerInformer.
func (v *version) DNSLoadBalancers() DNSLoadBalancerInformer {
	return &dNSLoadBalancerInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// DNSRecords returns a DNSRecordInformer.
func (v *version) DNSRecords() DNSRecordInformer {
	return &dNSRecordInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
