---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnsdomain.devops.snapp.ir
spec:
  group: devops.snapp.ir
  scope: Clustered
  names:
    plural: dnsdomains
    singular: dnsdomain
    kind: DNSDomain
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                pattern: '^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$'
          status:
            type: object
            properties:
              generation:
                type: string
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnsrecord.devops.snapp.ir
spec:
  group: devops.snapp.ir
  scope: Clustered
  names:
    plural: dnsrecords
    singular: dnsrecord
    kind: DNSRecord
    shortnames:
    - rec
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              domain:
                type: string    # Require a validating webhook
                pattern: '^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$'
              name:
                type: string
                pattern: '^(@|\*|((?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]))$'
              type:
                type: string
                pattern: 'A|AAAA|NS|CNAME|TXT|MX|SRV'
              enabled:
                type: boolean
                default: true
              health-check:
                type: object
                properties:
                  oneOf:
                    icmp:
                      type: object
                      properties:
                        server:
                          type: string
                    tcp:
                      type: object
                      properties:
                        server:
                          type: string
                        port:
                          type: int32
                          minimum: 0
                          maximum: 65535
                    http:
                      type: object
                      properties:
                        server:
                          type: string
              weight:
                type: int32
                minimum: 0
                maximum: 100
                default: 1
              ttl:
                type: int32
                minimum: 0
                maximum: 65535
                default: 30
              value:
                type: string
              port:
                type: int32
                minimum: 0
                maximum: 65535
              priority:
                type: int32
                minimum: 0
                maximum: 65535
          status:
            type: object
            properties:
              generation:
                type: string
    subresources:
      status: {}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition:
metadata:
  name: dnsloadbalancer.devops.snapp.ir
spec:
  group: devops.snapp.ir
  scope: Clustered
  names:
    singular: dnsloadbalancer
    plural: dnsloadbalancers
    kind: DNSLoadBalancer
    shortnames:
    - lb
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              domain:
                type: string
                pattern: '^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$'
              name:
                type: string
                pattern: '^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$'
              type:
                type: string
                pattern: 'A|AAAA|NS|CNAME|TXT|MX|SRV'
              value:
                type: string
              port:
                type: int32
                minimum: 0
                maximum: 65535
              enabled:
                type: boolean
                default: true
          status:
            type: object
            properties:
              enabled:
                type: boolean
    subresources:
      status: {}
---
