---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnsdomain.devops.snapp.ir
spec:
  group: devops.snapp.ir
  scope: Clustered
  names:
    plural: dnsdomains
    singular: dnsdomain
    kind: DNSDomain
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                pattern: '^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$'
            required: ["name"]
            preserveUnknownFields: false
          status:
            type: object
            properties:
              generation:
                type: string
        required: ["spec"]
    subresources:
      status: {}
