---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition:
metadata:
  name: dnsloadbalancer.devops.snapp.ir
spec:
  group: devops.snapp.ir
  scope: Clustered
  names:
    singular: dnsloadbalancer
    plural: dnsloadbalancers
    kind: DNSLoadBalancer
    shortnames:
    - lb
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              domain:
                type: string
                pattern: '^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$'
              name:
                type: string
                pattern: '^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9][a-z0-9-]{0,61}[a-z0-9]$'
              type:
                type: string
                enum: ['A', 'AAAA', 'NS', 'CNAME', 'TXT', 'MX', 'SRV']
              value:
                type: string
              enabled:
                type: boolean
                default: true
            required: ["domain", "name", "type", "value"]
            preserveUnknownFields: false
          status:
            type: object
            properties:
              enabled:
                type: boolean
              generation:
                type: string
    subresources:
      status: {}
